### ISSUE TITLE
Broken Raspberry Pi Simualtor Link

### ISSUE THREAD

**Issue by alexandruradovici** [wyliodrinstudio/WyliodrinSTUDIO#48]
### Description

The documentation link from the Raspberry Pi Simulator is broken. It points to https://wyliodrinstudio.readthedocs.io/en/latest/simulator_raspberrypi.html instead of https://wyliodrinstudio.readthedocs.io/en/latest/simulators/raspberrypi.html.

### Steps to Reproduce

1. Start Wyliodrin STUDIO
2. Open the CONNECT manager
3. Connect to the Raspberry Pi Simulator
4. Go to the Raspberry Pi Simulator Tab
5. Click the question mark button on the upper right

**Expected behavior:** Show the documentation

**Actual behavior:** Shows a page not found error

**Reproduces how often:** All the time

### Version

Wyliodrin STUDIO:
2.3.1

Wyliodrin STUDIO platform:
   [x] downloaded (electron)
   [x] web (browser)

OS name: macOS
OS version: 11.0

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by 96RadhikaJadhav** [comment]
@alexandruradovici Can I work on it?

**Comment by alexandruradovici** [comment]
Sure, yes!

**Comment by 96RadhikaJadhav** [comment]
@alexandruradovici I have created a PR. Can you please check it?
