### ISSUE TITLE
How to install on Linux

### ISSUE THREAD

**Issue by Napoleon-BlownApart** [wyliodrinstudio/WyliodrinSTUDIO#79]
Thanks for working on what appears to be an interesting tool, however I am unable to get it going.
From the (Getting Started)[https://wyliodrinstudio.readthedocs.io/en/latest/start.html] page, the relevant links I tried were all broken.
Both  the Install for Mac and Linux give HTTPD error messages with the `NoSuchBucket` keyword.

I have cloned the repo and would like to try it under (Ubuntu20, but happy to switch to something else if needed) Linux running in a VM.  Are the build instructions for Linux platforms? Nothing in the README.md file.

**Comment by alexandruradovici** [comment]
Thank you for pointing out the broken links. In the meantime, please follow the instruction from https://wyliodrin.studio.
