### ISSUE TITLE
How to change coding language in the Wyliodrin Studio after making an initial choice.

### ISSUE THREAD

**Issue by Napoleon-BlownApart** [wyliodrinstudio/WyliodrinSTUDIO#80]
I downloaded the Mac version and ran it.  After creating an application, using C in this case, I can't figure out how to either create a new application nor how to change to another coding language.
Sorry if this is actually very simple.

**Comment by alexandruradovici** [comment]
Hi,

You should be able to create a new Application. In the top toolbar, you have a button with a folder icon. Click the button to open the Projects Library. On the bottom of the library dialog, you have a button called Create New Application.
